version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout

      - run:
          name: LogIn to docker hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: Build image 
          command: |
            docker build --no-cache -t ccbash/ansible:$CIRCLE_BRANCH -f $(DIR)/$(FILE)$${SUFFIX} .
      
      - run: 
          name: Push Image
          command: |
            docker push ccbash/ansible:$CIRCLE_BRANCH